### ISSUE TITLE
Error with importMeshes.py from Flywire

### ISSUE THREAD

**Issue by drosorouv** [connectome-neuprint/neuVid#206]
Hello, 
I really appreciate this very cool tool and been using it with hemibrain so far. Now I am struggling a bit with importing data from Flywire:
I followed the instructions in the documentation and importNg.py and the following FetchMeshes.py work fine. However, when I then run importMeshes.py, I receive the following:

(neuVid-NG) C:\>"C:\Blender\blender.exe" --background --python neuVid/neuVid/importMeshes.py -- -i "D:\neuvid\ex4.json"
Blender 4.3.2 (hash 32f5fdce0a0a built 2024-12-17 03:35:23)
neuVid 1.49.0
Using output Blender file: 'D:\neuvid\ex4.blend'
Using SWC cross-sectional vertex count: 12
Using SWC axon radius factor: 10
Using SWC dendrite radius factor: 15
Parsing neuron IDs...
Done
Using separate .blend files for neurons: False
Assigning colors...
Done
Importing 1 neuron meshes
0: 0 / 1 (0.17 secs)
OBJ import of '720575940626622480.obj' took 47.82 ms
Added object 'Neuron.720575940626622480'

ERROR: cannot import neuron file 'D:\neuvid\precomputed___gs___flywire_v141_m783\720575940626622480.obj' for ID 720575940626622480:

'Material' object has no attribute 'shadow_method'
Done
Computing bounding boxes for neuron meshes...
Done
Assigning ROI materials...
Importing synapse meshes...
Done
Assigning synapse materials...
Done
Adding bounds...
Done
Writing D:\neuvid\ex4.blend
Info: Saved "ex4.blend"

Importing started at 2025-02-24 10:19:12.243693
Importing ended at 2025-02-24 10:19:12.491120
Elapsed time: 0:00:00.247427

ERROR: could not download/find mesh .obj files for the following neurons:
[720575940626622480]

Blender quit

It still writes a .blend file which I can then use to run addAnimation.py. But when I try to modify the animation with fading or colors it wont work. So I guess there is some issue with the meshes not being properly downloaded or assigned.

How could I solve this?

Best,
Rouven

**Comment by drosorouv** [comment]
I noticed I was using Blender 4.3, which caused this Error. 
With Blender 3.6 everything works perfect

**Comment by hubbardp** [comment]
Interesting.  Just yesterday I did some work with FlyWire using Blender 4.2.1 and it was working for me.  I'll get 4.3 and test it, to see if I can find the problem.
